	mv  adityaprabhu.1272 Pierre_de_Fermat
	mv basakdeepta10 Joseph_Louis_Lagrange
	mv basisthaamitkumar2 Maryam_Mirzakhani
	mv devansh4178 Sophie_Germain
	mv doll.poll18 Diophantus_of_Alexandria
	mv eshanjaffarof1729 Isaac_Newton
	mv  gangvish07 John_Nash
	mv  gbuddyv George_Boole
	mv krrissh001 Sun_Tzu
	mv mananroychoudhury Evariste_Galois
	mv meryanhere Emmy_Noether
	mv  samujjal101 John_Napier
	mv samya.riju Ada_Lovelace
	mv sanchitabhowmick82 Bernhard_Riemann
	mv sougata543 Sofia_Kovalevskaya
	mv soumyadeepma Srinivasa_Ramanujan
	mv uttiyadas42 Marin_Mersenne
	mv var.prer Florence_Nightingale
	mv varunb22.2004 Muhammad_Al_Khwarizmi
