	mkdir adityaprabhu.1272
	mkdir basakdeepta10
	mkdir basisthaamitkumar2
	mkdir devansh4178
	mkdir doll.poll18
	mkdir eshanjaffarof1729
	mkdir  gangvish07
	mkdir  gbuddyv
	mkdir krrissh001
	mkdir mananroychoudhury
	mkdir meryanhere
	mkdir  samujjal101
	mkdir samya.riju
	mkdir sanchitabhowmick82
	mkdir sougata543
	mkdir soumyadeepma
	mkdir uttiyadas42
	mkdir var.prer
	mkdir varunb22.2004
